package com.example.smartbudget;

import com.example.smartbudget.Handler.AddBudgetHandler;
import com.example.smartbudget.Handler.AddCategoryHandler;
import com.example.smartbudget.Handler.AddExpenditureHandler;
import com.example.smartbudget.Handler.DeleteBudgetHandler;
import com.example.smartbudget.Handler.DeleteCategoryHandler;
import com.example.smartbudget.Handler.DeleteExpenditureHandler;
import com.example.smartbudget.Handler.GetBudgetsHandler;
import com.example.smartbudget.Handler.GetCategoriesHandler;
import com.example.smartbudget.Handler.GetExpendituresForDayHandler;
import com.example.smartbudget.Handler.LoginHandler;
import com.example.smartbudget.Handler.RegisterHandler;
import com.example.smartbudget.Handler.UpdateBudgetHandler;
import com.example.smartbudget.Request.AddBudgetRequest;
import com.example.smartbudget.Request.AddCategoryRequest;
import com.example.smartbudget.Request.AddExpenditureRequest;
import com.example.smartbudget.Request.DeleteBudgetRequest;
import com.example.smartbudget.Request.DeleteCategoryRequest;
import com.example.smartbudget.Request.DeleteExpenditureRequest;
import com.example.smartbudget.Request.EditCategoriesRequest;
import com.example.smartbudget.Request.EditExpendituresRequest;
import com.example.smartbudget.Request.GetBudgetsRequest;
import com.example.smartbudget.Request.GetCategoriesRequest;
import com.example.smartbudget.Request.GetExpendituresForDayRequest;
import com.example.smartbudget.Request.GetStatsRequest;
import com.example.smartbudget.Request.LoadYearRequest;
import com.example.smartbudget.Request.LoginRequest;
import com.example.smartbudget.Request.ReadBudgetRequest;
import com.example.smartbudget.Request.RegisterRequest;
import com.example.smartbudget.Request.ReportDayRequest;
import com.example.smartbudget.Request.UpdateBudgetRequest;
import com.example.smartbudget.Response.AddBudgetResponse;
import com.example.smartbudget.Response.AddCategoryResponse;
import com.example.smartbudget.Response.AddExpenditureResponse;
import com.example.smartbudget.Response.DeleteBudgetResponse;
import com.example.smartbudget.Response.DeleteCategoryResponse;
import com.example.smartbudget.Response.DeleteExpenditureResponse;
import com.example.smartbudget.Response.EditCategoriesResponse;
import com.example.smartbudget.Response.EditExpendituresResponse;
import com.example.smartbudget.Response.GetBudgetResponse;
import com.example.smartbudget.Response.GetCategoriesResponse;
import com.example.smartbudget.Response.GetExpenditureForDayResponse;
import com.example.smartbudget.Response.GetStatsResponse;
import com.example.smartbudget.Response.LoadYearResponse;
import com.example.smartbudget.Response.LoginResponse;
import com.example.smartbudget.Response.ReadBudgetResponse;
import com.example.smartbudget.Response.RegisterResponse;
import com.example.smartbudget.Response.ReportDayResponse;
import com.example.smartbudget.Response.UpdateBudgetResponse;

public interface IBackend {
    AddBudgetResponse addBudget(AddBudgetRequest request);
    AddExpenditureResponse addExpenditure(AddExpenditureRequest request);
    ReadBudgetResponse readBudget(ReadBudgetRequest request);
    DeleteBudgetResponse deleteBudget(DeleteBudgetRequest request);
    UpdateBudgetResponse updateBudget(UpdateBudgetRequest request);
    LoadYearResponse loadYear(LoadYearRequest request);
    ReportDayResponse reportDay(ReportDayRequest request);
    EditExpendituresResponse editExpenditures(EditExpendituresRequest request);
    GetStatsResponse getStats(GetStatsRequest request);
    EditCategoriesResponse editCategories(EditCategoriesRequest request);
    AddCategoryResponse addCategory(AddCategoryRequest request);
    LoginResponse login(LoginRequest request);
    RegisterResponse register(RegisterRequest request);
    GetBudgetResponse getBudgets(GetBudgetsRequest request);
    GetExpenditureForDayResponse getExpenditures(GetExpendituresForDayRequest request);
    GetCategoriesResponse getCategories(GetCategoriesRequest request);
    DeleteExpenditureResponse deleteExpenditure(DeleteExpenditureRequest request);
    DeleteCategoryResponse deleteCategory(DeleteCategoryRequest request);
}
